name: quantum_possibilities_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  readmore: ^3.0.0
  share_plus: ^9.0.0
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2 # Icons
  get: 4.6.6 # State Management
  emoji_picker_flutter: ^2.2.0 # Emoji picker
  get_storage: ^2.1.1 # Local Storage
  connectivity_plus: ^5.0.2 # Check internet connection
  dio: ^5.4.1 # Network call
  http_parser: ^4.0.2 # Network call
  flutter_easyloading: ^3.0.5 # Loader
  intl: ^0.19.0 # Date formate
  flutter_holo_date_picker: ^1.1.3 # Date Picker
  video_player: ^2.8.3 # Playing Viewo
  expandable_text: ^2.3.0 # Expandable Text
  flutter_reaction_button: ^3.0.0+3 # Reaction
  flutter_staggered_animations: ^1.1.1 # Animation
  carousel_slider: ^4.2.1
  newsfeed_multiple_imageview: ^1.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  screenshot: ^2.3.0 #caputre screenshot
  photo_manager: ^3.0.0
  flutter_rating_bar: ^4.0.1 #rating
  flutter_svg: ^2.0.10+1 #svg
  url_launcher: ^6.2.6   #launch_url
  shimmer: ^3.0.0 #simmer
  chewie: ^1.8.1
  visibility_detector: ^0.4.0+2



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: fonts/SfProDisplay-Regular.otf
          weight: 500
        - asset: fonts/SfProDisplay-Medium.otf
          weight: 600
        - asset: fonts/SfProDisplay-Bold.otf
          weight: 700
  
  assets:
    - assets/logo/
    - assets/image/
    - assets/icon/
    - assets/icon/appbar/
    - assets/icon/navbar/
    - assets/icon/reaction/
    - assets/icon/create_post/
    - assets/icon/user_menu/
    - assets/icon/post_action/
    - assets/icon/comment/
    - assets/other/
    - assets/icon/live_event/


